import type { ChipOption } from "../../../types/chips";

export const categoryTree: ChipOption[] = [
  {
    id: "everyday_help",
    label: "Apua arkeen",
    value: "everyday_help",
    level: 1,
    contexts: ["browse", "listing", "profile", "onboarding"],
    children: [
      {
        id: "errands",
        label: "Kauppa ja asiointi",
        value: "errands",
        parentId: "everyday_help",
        level: 2,
        children: [
          { id: "grocery_help", label: "Kaupassakäynti", value: "grocery_help", parentId: "errands", level: 3 },
          { id: "pharmacy_help", label: "Apteekkiasiat", value: "pharmacy_help", parentId: "errands", level: 3 },
          { id: "package_pickup", label: "Paketin nouto", value: "package_pickup", parentId: "errands", level: 3 },
          { id: "official_errands", label: "Asiointiapu", value: "official_errands", parentId: "errands", level: 3 },
        ],
      },
      {
        id: "carrying_moving",
        label: "Kanto ja muutto",
        value: "carrying_moving",
        parentId: "everyday_help",
        level: 2,
        children: [
          { id: "carry_items", label: "Tavaran kantaminen", value: "carry_items", parentId: "carrying_moving", level: 3 },
          { id: "small_move", label: "Pieni muuttoapu", value: "small_move", parentId: "carrying_moving", level: 3 },
          { id: "move_furniture", label: "Huonekalun siirto", value: "move_furniture", parentId: "carrying_moving", level: 3 },
          { id: "car_help", label: "Auton kanssa auttaminen", value: "car_help", parentId: "carrying_moving", level: 3 },
        ],
      },
      {
        id: "home_small_tasks",
        label: "Koti ja pienet työt",
        value: "home_small_tasks",
        parentId: "everyday_help",
        level: 2,
        children: [
          { id: "hang_picture", label: "Taulun kiinnitys", value: "hang_picture", parentId: "home_small_tasks", level: 3 },
          { id: "drilling_help", label: "Porausapu", value: "drilling_help", parentId: "home_small_tasks", level: 3 },
          { id: "shelf_install", label: "Hyllyn asennus", value: "shelf_install", parentId: "home_small_tasks", level: 3 },
          { id: "light_cleaning", label: "Kevyt siivous", value: "light_cleaning", parentId: "home_small_tasks", level: 3 },
          { id: "furniture_assembly", label: "Huonekalun kokoaminen", value: "furniture_assembly", parentId: "home_small_tasks", level: 3 },
        ],
      },
      {
        id: "away_help",
        label: "Poissaoloapu",
        value: "away_help",
        parentId: "everyday_help",
        level: 2,
        children: [
          { id: "water_plants", label: "Kasvien kastelu", value: "water_plants", parentId: "away_help", level: 3 },
          { id: "collect_mail", label: "Postien haku", value: "collect_mail", parentId: "away_help", level: 3 },
          { id: "key_handover", label: "Avainten luovutus", value: "key_handover", parentId: "away_help", level: 3 },
          { id: "home_check", label: "Kodin tarkistus", value: "home_check", parentId: "away_help", level: 3 },
        ],
      },
      {
        id: "pets_everyday",
        label: "Lemmikit",
        value: "pets_everyday",
        parentId: "everyday_help",
        level: 2,
        children: [
          { id: "dog_walking", label: "Koiran ulkoilutus", value: "dog_walking", parentId: "pets_everyday", level: 3 },
          { id: "pet_feeding", label: "Ruokinta", value: "pet_feeding", parentId: "pets_everyday", level: 3 },
          { id: "short_pet_sitting", label: "Lyhyt vahtiminen", value: "short_pet_sitting", parentId: "pets_everyday", level: 3 },
          { id: "pet_home_visit", label: "Vierailu kotona", value: "pet_home_visit", parentId: "pets_everyday", level: 3 },
        ],
      },
    ],
  },
  {
    id: "items_to_borrow",
    label: "Tavarat lainaan",
    value: "items_to_borrow",
    level: 1,
    contexts: ["browse", "listing", "profile", "onboarding"],
    children: [
      {
        id: "tools",
        label: "Työkalut",
        value: "tools",
        parentId: "items_to_borrow",
        level: 2,
        children: [
          { id: "drill", label: "Porakone", value: "drill", parentId: "tools", level: 3 },
          { id: "ladder", label: "Tikkaat", value: "ladder", parentId: "tools", level: 3 },
          { id: "screwdriver", label: "Ruuvinväännin", value: "screwdriver", parentId: "tools", level: 3 },
          { id: "sander", label: "Hiomakone", value: "sander", parentId: "tools", level: 3 },
        ],
      },
      {
        id: "transport_carrying",
        label: "Kuljetus ja kantaminen",
        value: "transport_carrying",
        parentId: "items_to_borrow",
        level: 2,
        children: [
          { id: "hand_truck", label: "Nokkakärryt", value: "hand_truck", parentId: "transport_carrying", level: 3 },
          { id: "trailer", label: "Peräkärry", value: "trailer", parentId: "transport_carrying", level: 3 },
          { id: "moving_boxes", label: "Muuttolaatikot", value: "moving_boxes", parentId: "transport_carrying", level: 3 },
          { id: "carrying_straps", label: "Kantoliinat", value: "carrying_straps", parentId: "transport_carrying", level: 3 },
        ],
      },
      {
        id: "home_party",
        label: "Koti ja juhlat",
        value: "home_party",
        parentId: "items_to_borrow",
        level: 2,
        children: [
          { id: "serving_dishes", label: "Tarjoiluastiat", value: "serving_dishes", parentId: "home_party", level: 3 },
          { id: "folding_table", label: "Taittopöytä", value: "folding_table", parentId: "home_party", level: 3 },
          { id: "chairs", label: "Tuolit", value: "chairs", parentId: "home_party", level: 3 },
          { id: "decorations", label: "Koristeet", value: "decorations", parentId: "home_party", level: 3 },
        ],
      },
      {
        id: "electronics",
        label: "Elektroniikka",
        value: "electronics",
        parentId: "items_to_borrow",
        level: 2,
        children: [
          { id: "charger", label: "Laturi", value: "charger", parentId: "electronics", level: 3 },
          { id: "adapter", label: "Adapteri", value: "adapter", parentId: "electronics", level: 3 },
          { id: "projector", label: "Projektori", value: "projector", parentId: "electronics", level: 3 },
          { id: "speaker", label: "Kaiutin", value: "speaker", parentId: "electronics", level: 3 },
        ],
      },
      {
        id: "hobby_gear",
        label: "Harrastusvälineet",
        value: "hobby_gear",
        parentId: "items_to_borrow",
        level: 2,
        children: [
          { id: "sports_gear", label: "Urheiluvälineet", value: "sports_gear", parentId: "hobby_gear", level: 3 },
          { id: "camping_gear", label: "Retkeilyvälineet", value: "camping_gear", parentId: "hobby_gear", level: 3 },
          { id: "board_games", label: "Lautapelit", value: "board_games", parentId: "hobby_gear", level: 3 },
          { id: "games", label: "Pelit", value: "games", parentId: "hobby_gear", level: 3 },
        ],
      },
      {
        id: "pet_items",
        label: "Lemmikkitarvikkeet",
        value: "pet_items",
        parentId: "items_to_borrow",
        level: 2,
        children: [
          { id: "pet_carrier", label: "Kuljetuskoppa", value: "pet_carrier", parentId: "pet_items", level: 3 },
          { id: "leash", label: "Hihna", value: "leash", parentId: "pet_items", level: 3 },
          { id: "food_bowl", label: "Ruokakuppi", value: "food_bowl", parentId: "pet_items", level: 3 },
          { id: "other_pet_item", label: "Muu tarvike", value: "other_pet_item", parentId: "pet_items", level: 3 },
        ],
      },
    ],
  },
  {
    id: "skills_guidance",
    label: "Osaaminen",
    value: "skills_guidance",
    level: 1,
    contexts: ["browse", "listing", "profile", "onboarding"],
    children: [
      {
        id: "digital_help",
        label: "Digiapu",
        value: "digital_help",
        parentId: "skills_guidance",
        level: 2,
        children: [
          { id: "phone_help", label: "Puhelin", value: "phone_help", parentId: "digital_help", level: 3 },
          { id: "computer_help", label: "Tietokone", value: "computer_help", parentId: "digital_help", level: 3 },
          { id: "printer_help", label: "Tulostin", value: "printer_help", parentId: "digital_help", level: 3 },
          { id: "app_help", label: "Sovellukset", value: "app_help", parentId: "digital_help", level: 3 },
        ],
      },
      {
        id: "languages_study",
        label: "Kielet ja opiskelu",
        value: "languages_study",
        parentId: "skills_guidance",
        level: 2,
        children: [
          { id: "language_practice", label: "Kieliharjoittelu", value: "language_practice", parentId: "languages_study", level: 3 },
          { id: "homework_help", label: "Läksyapu", value: "homework_help", parentId: "languages_study", level: 3 },
          { id: "writing_help", label: "Kirjoittaminen", value: "writing_help", parentId: "languages_study", level: 3 },
          { id: "study_support", label: "Opiskelutuki", value: "study_support", parentId: "languages_study", level: 3 },
        ],
      },
      {
        id: "creative_help",
        label: "Luova apu",
        value: "creative_help",
        parentId: "skills_guidance",
        level: 2,
        children: [
          { id: "photography", label: "Valokuvaus", value: "photography", parentId: "creative_help", level: 3 },
          { id: "graphic_design", label: "Graafinen suunnittelu", value: "graphic_design", parentId: "creative_help", level: 3 },
          { id: "text_editing", label: "Tekstin editointi", value: "text_editing", parentId: "creative_help", level: 3 },
          { id: "crafts", label: "Käsityöt", value: "crafts", parentId: "creative_help", level: 3 },
        ],
      },
      {
        id: "everyday_advice",
        label: "Arjen neuvot",
        value: "everyday_advice",
        parentId: "skills_guidance",
        level: 2,
        children: [
          { id: "practical_tips", label: "Käytännön vinkit", value: "practical_tips", parentId: "everyday_advice", level: 3 },
          { id: "local_tips", label: "Aluevinkit", value: "local_tips", parentId: "everyday_advice", level: 3 },
          { id: "forms_help", label: "Lomakkeiden täyttö", value: "forms_help", parentId: "everyday_advice", level: 3 },
          { id: "small_life_admin", label: "Pieni asiointineuvo", value: "small_life_admin", parentId: "everyday_advice", level: 3 },
        ],
      },
    ],
  },
  {
    id: "together",
    label: "Yhdessä tekeminen",
    value: "together",
    level: 1,
    contexts: ["browse", "listing", "profile", "onboarding"],
    children: [
      {
        id: "outdoors_exercise",
        label: "Ulkoilu ja liikunta",
        value: "outdoors_exercise",
        parentId: "together",
        level: 2,
        children: [
          { id: "walk_together", label: "Lenkkiseura", value: "walk_together", parentId: "outdoors_exercise", level: 3 },
          { id: "gym_friend", label: "Salikaveri", value: "gym_friend", parentId: "outdoors_exercise", level: 3 },
          { id: "ball_games", label: "Pallopelit", value: "ball_games", parentId: "outdoors_exercise", level: 3 },
          { id: "outdoor_time", label: "Ulkoilu", value: "outdoor_time", parentId: "outdoors_exercise", level: 3 },
        ],
      },
      {
        id: "coffee_company",
        label: "Kahvi ja seura",
        value: "coffee_company",
        parentId: "together",
        level: 2,
        children: [
          { id: "coffee_chat", label: "Kahviseura", value: "coffee_chat", parentId: "coffee_company", level: 3 },
          { id: "conversation", label: "Keskustelu", value: "conversation", parentId: "coffee_company", level: 3 },
          { id: "meet_neighbors", label: "Tutustuminen", value: "meet_neighbors", parentId: "coffee_company", level: 3 },
          { id: "spend_time", label: "Yhteinen ajanvietto", value: "spend_time", parentId: "coffee_company", level: 3 },
        ],
      },
      {
        id: "hobbies",
        label: "Harrastukset",
        value: "hobbies",
        parentId: "together",
        level: 2,
        children: [
          { id: "board_game_group", label: "Lautapelit", value: "board_game_group", parentId: "hobbies", level: 3 },
          { id: "music", label: "Musiikki", value: "music", parentId: "hobbies", level: 3 },
          { id: "book_club", label: "Lukupiiri", value: "book_club", parentId: "hobbies", level: 3 },
          { id: "craft_group", label: "Käsityöt", value: "craft_group", parentId: "hobbies", level: 3 },
        ],
      },
      {
        id: "events_talkoot",
        label: "Talkoot ja tapahtumat",
        value: "events_talkoot",
        parentId: "together",
        level: 2,
        children: [
          { id: "housing_talkoot", label: "Taloyhtiötalkoot", value: "housing_talkoot", parentId: "events_talkoot", level: 3 },
          { id: "flea_market", label: "Kirppis", value: "flea_market", parentId: "events_talkoot", level: 3 },
          { id: "yard_event", label: "Pihatapahtuma", value: "yard_event", parentId: "events_talkoot", level: 3 },
          { id: "community_walk", label: "Yhteislenkki", value: "community_walk", parentId: "events_talkoot", level: 3 },
        ],
      },
      {
        id: "food_cooking",
        label: "Ruoka ja yhteiskokkaus",
        value: "food_cooking",
        parentId: "together",
        level: 2,
        children: [
          { id: "baking", label: "Leivonta", value: "baking", parentId: "food_cooking", level: 3 },
          { id: "cook_together", label: "Yhteiskokkaus", value: "cook_together", parentId: "food_cooking", level: 3 },
          { id: "recipe_tips", label: "Reseptivinkit", value: "recipe_tips", parentId: "food_cooking", level: 3 },
          { id: "extra_food", label: "Ylimääräinen ruoka", value: "extra_food", parentId: "food_cooking", level: 3 },
        ],
      },
    ],
  },
];